### ISSUE TITLE
Requirements for a new release?

### ISSUE THREAD

**Issue by fschulze** [Pylons/pyramid_layout#40]
What would be required for a new release?

I just evaluated this and it pretty much does what I would like it to do. I would spend the time to fix some stuff I identified if that would lead to a release. I think I already am a contributor to Pylons stuff.

I personally still need compatibility for Pyramid 1.x, but also 2.x. So the first thing I identified is PR #35 which doesn't seem to have a test which actually shows the issue, so I would try to write one and add testing with ``pyramid<2``.

How important are #38 (I currently get coverage failures with tox) and #39? I might also hit #33 at some point, so I would most likely take a look at that as well.

**Comment by fschulze** [comment]
@chrisrossi @bbangert @mmerickel I would also be willing to take over maintenance and releases if you add me to PyPI or can pylonsbot do releases there?

**Comment by fschulze** [comment]
I've used pyramid_layout for a while now and it doesn't quite fit my needs after all. It isn't very complex, so it is easier to roll my own.

**Comment by mmerickel** [comment]
@fschulze I had been waiting to see if @chrisrossi would respond because I don't own this package but at this point, despite your understandable frustration, I can hand it over to you if you're still willing.

**Comment by fschulze** [comment]
@mmerickel I'm not frustrated. I only discovered that my initial impression of how I could use pyramid_layout was false and I have different requirements (or I'm using it wrong).

**Comment by Estartu** [comment]
We are using pyramid_layout very much. I've build my own package right now. But a new release including et least pull request #35 would be nice
